#!/usr/bin/env python
# -*- coding: utf-8 -*-
import pytest

from data_helper.create_data.MES.sales_manage.sales_order_data import deleteSaleOrder
from util.api_util.service.basic_data.supplier_data import SupplierData


@pytest.fixture()
def delete_sales_order_data():
    """  后置删除销售订单 """
    yield
    print('=------------------------------------- 正在进行后置数据清理...... -----------------------------------------=')
    SupplierData().delete_supplier()

